2025-06-11 22:20:35,011 ERROR: Exception on /login [GET] [in C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\app\routes.py", line 55, in login
    return render_template('login.html', title='Sign In', form = form)
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\app\templates\login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\app\templates\base.html", line 58, in top-level template code
    {%block content%}{%endblock%}
    ^^^^^^^^^^^^^
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\app\templates\login.html", line 10, in block 'content'
    <a href="{{ url_for('reset_password_request')}}">Click to Reset It</a>
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'reset_password' instead?
2025-06-11 22:29:11,141 INFO: Microblog startup [in C:\Users\Hi\Desktop\project cá nhân\Microblog\app\__init__.py:43]
2025-06-11 22:29:15,480 ERROR: Exception on /login [GET] [in C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\app\routes.py", line 55, in login
    return render_template('login.html', title='Sign In', form = form)
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\app\templates\login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\app\templates\base.html", line 58, in top-level template code
    {%block content%}{%endblock%}
    ^^^^^^^^^^^^^
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\app\templates\login.html", line 10, in block 'content'
    <a href="{{ url_for('reset_password_request')}}">Click to Reset It</a>
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'reset_password' instead?
2025-06-11 22:33:02,849 INFO: Microblog startup [in C:\Users\Hi\Desktop\project cá nhân\Microblog\app\__init__.py:43]
2025-06-11 22:33:06,022 ERROR: Exception on /login [GET] [in C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\app\routes.py", line 55, in login
    return render_template('login.html', title='Sign In', form = form)
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\app\templates\login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\app\templates\base.html", line 58, in top-level template code
    {%block content%}{%endblock%}
    ^^^^^^^^^^^^^
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\app\templates\login.html", line 10, in block 'content'
    <a href="{{ url_for('reset_password_request')}}">Click to Reset It</a>
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Hi\Desktop\project cá nhân\Microblog\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'reset_password' instead?
2025-06-11 22:40:45,028 INFO: Microblog startup [in C:\Users\Hi\Desktop\project cá nhân\Microblog\app\__init__.py:43]
